version: '3.8'
services:
  react:
    build:
      context: .
      dockerfile: ./docker/react/Dockerfile
    image: yanokrake_react
    container_name: yanokrake_react_container
    tty: true
    volumes:
      - ./react-app:/app/react
      #- .:/app:cached
    ports:
      - 3000:3000
  go:
    build:
      context: .
      dockerfile: ./docker/golang/Dockerfile
    image: yanokrake_go
    container_name: yanokrake_go_container
    ports:
      - 8000:8000
    tty: true
    volumes:
      - ./go-app:/app/go
  # mysql:
  #   build:
  #     context: .
  #     dockerfile: ./docker/mysql/Dockerfile
  #   image: yanokrake_mysql
  #   container_name: yanokrake_mysql_container
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: react-go-app
  #     TZ: 'Asia/Tokyo'
  #   volumes:
  #     - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
  #     - ./docker/mysql/conf.d:/etc/mysql/conf.d
  #     - ./docker/mysql/mysql_data:/var/lib/mysql
  #   ports:
  #   - 3306:3306
  #   links:
  #     - go